# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Career"
  url = "#career"
  weight = 20

[[main]]
  name = "Teachings"
  url = "#teachings"
  weight = 40

 
[[main]]
  name = "Activities"
  url = "#activities"
  weight = 50

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 55

[[main]]
  name = Selected Publications"
  url = "#selpublications"
  weight = 57
  
[[main]]
  name = "Publications"
  url = "#publications"
  weight = 60
 
[[main]]
  name = "Collaborations"
  url = "#collaborations"
  weight = 70

[[main]]
  name = "Contacts"
  url = "#contacts"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.

[[main]]
  name = "CV"
  url = "media/resume.pdf"
  weight = 90
