[build]
  command = "bash netlify/build-hugo-0.80.sh"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "bash netlify/build-hugo-0.80.sh"

[context.branch-deploy]
  command = "bash netlify/build-hugo-0.80.sh"

[[redirects]]
  from = "/zonaorientale/static/*"
  to = "/zonaorientale/:splat"
  status = 301

[[redirects]]
  from = "/zonaorientale/share/news/:id"
  to = "/.netlify/functions/news-share?id=:id"
  status = 200

[[redirects]]
  from = "/fantapetillomantramanager/share/news/:id"
  to = "/.netlify/functions/news-share?id=:id&league=fantapetillomantramanager"
  status = 200
